name: Generate Daily Blog Posts

on:
  schedule:
    # Runs daily at 00:00 UTC. Adjust as needed.
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit changes back to the repo
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Specify a version like '3.11' or use '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily workflow script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        run: |
          python main_daily_workflow.py --num_posts 2 --country us # Adjust params as needed

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@users.noreply.github.com'
          # Stage all changes. If specific files are preferred, list them.
          git add . 
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated daily blog post generation"
            git push
          fi
