name: Delete All Blog Posts

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  delete_posts:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit changes back to the repo
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Delete HTML files from blog directory
        run: |
          echo "Deleting HTML files from blog/ ..."
          find blog/ -maxdepth 1 -type f -name "*.html" -delete
          echo "HTML files in blog/ deleted."

      - name: Delete Markdown and Meta files from posts directory
        run: |
          echo "Deleting Markdown and Meta files from posts/ ..."
          find posts/ -maxdepth 1 -type f \( -name "*.md" -o -name "*.meta" \) -delete
          echo "Markdown and Meta files in posts/ deleted."

      - name: Clear posts.json
        run: |
          echo "Clearing posts.json..."
          echo "[]" > posts.json
          echo "posts.json cleared."

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@users.noreply.github.com'
          # Stage all changes.
          git add blog/ posts/ posts.json
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No content changes to commit."
          else
            git commit -m "Reset: Deleted all blog posts and cleared posts.json"
            git push
            echo "Changes committed and pushed."
          fi
